version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes: