export const VIDEOS = [
    { id: 'ZcZVtt-baas', name: 'Маша и Медведь - Сборник лучших серий' },
    { id: 'nib9haDfXkU', name: 'Peppa Pig Official Channel | Peppa Pig\'s Best Episodes' },
    { id: 'kFoYNforU4Y', name: 'Развивающие мультики - Большой Сборник для детей' },
    { id: 'qXcMNBQnQMM', name: 'Cocomelon - Nursery Rhymes | Kids Songs' },
    { id: 'To5yh3rDuRs', name: 'Фиксики - Большой сборник образовательных мультиков для детей' },
    { id: '_pWhx7l_48g', name: 'Blippi - Educational Videos for Kids' },
    { id: 'ppOWBAxT-Eg', name: 'Малышарики - Сборник веселых серий' },
    { id: 'fT-ciS7dk-U', name: 'Paw Patrol - Rescue Episodes' },
    { id: 'HIcNKigvJy0', name: 'Поезда и вагоны для детей. Виды вагонов железнодорожного транспорта' },
    { id: 'Psuuom9ZS5A', name: 'Super Simple Songs - Kids Songs' },
    { id: 'XqZsoesa55w', name: 'Baby Shark Dance - Sing and Dance!' },
    { id: '1axK79unKEY', name: 'Развивающие мультфильмы Совы - Уроки тетушки Совы' },
    { id: '6yklSe3Ud-A', name: 'Little Baby Bum - Nursery Rhymes & Kids Songs' },
    { id: 'OBjkNW11ujM', name: 'Лунтик - Новые серии' },
    { id: '3FszkGtTCCw', name: 'Mother Goose Club - Nursery Rhymes' },
    { id: 'vrLu-gdkG6I', name: 'Синий трактор - Развивающие песенки для детей' },
    { id: 'Hs0fNvQ0qaQ', name: 'Sesame Street - Educational Videos' },
    { id: 'jzZKgl_29bw', name: 'Барбоскины - Сборник мультфильмов' },
    { id: 'So-sOeKAkpw', name: 'Dave and Ava - Nursery Rhymes and Baby Songs' },
    { id: 'ptk68qC1woI', name: 'Ми-ми-мишки - Все серии подряд' },
    { id: 't6vApLGmp6E', name: 'ABC Song - Phonics Song for Children' },
    { id: '-Z95SxV8PZc', name: 'Смешарики - Познавательные мультики' },
    { id: 'GAqbpHKOhPU', name: 'Chu Chu TV - Nursery Rhymes & Kids Songs' },
    { id: 'ttinNltX1x4', name: 'Робокар Поли - Правила дорожного движения' },
    { id: 'uueDgAveDkQ', name: 'Numberblocks - Learn to Count' },
    { id: 'qPCbB-gH2Ew', name: 'Буба - Все серии подряд' },
    { id: 'KCJniIY2Uy4', name: 'Alphablocks - Learn to Read' },
    { id: 'KqrXCJ9JwlQ', name: 'Котики, вперед! - Развивающие мультики' },
    { id: 'NzCsLa_ec30', name: 'StoryBots Super Songs - Educational Songs' },
    { id: 'Qa1O4CwATcA', name: 'Грузовичок Лева - Мультики про машинки' },
    { id: 'bdNbUw5FIQo', name: 'Octonauts - Ocean Adventures' },
    { id: 'zxKK6EAwjdA', name: 'Царевны - Мультсериал для девочек' },
    { id: 'RIWRqjcbJcs', name: 'Pinkfong - Baby Shark and Friends' },
    { id: 'AmpqyQIyBY0', name: 'Четверо в кубе - Веселые приключения' },
    { id: 'XhpGp9d9jSA', name: 'Morphle - My Magic Pet Morphle' },
    { id: 'h2q0NQcAKzg', name: 'Домики - Познавательный мультсериал' },
    { id: '8deypue7SdQ', name: 'Badanamu - Nursery Rhymes and Kids Songs' },
    { id: 'S-zQ_LbrU7o', name: 'Ангел Бэби - Добрые мультики' },
    { id: 'DoULakpoynA', name: 'Bounce Patrol - Kids Songs' },
    { id: 'iuhiJPpzEUg', name: 'Бобр Добр - Мультсериал о дружбе' },
    { id: 'eUs3h7-jKIk', name: 'Talking Tom and Friends - Funny Episodes' },
    { id: 'zTqn-c-nD_w', name: 'Капитан Кракен - Морские приключения' },
    { id: 'KjUtidNMBDE', name: 'Caillou - Educational Cartoons' },
    { id: 'PM8o5hVHLzs', name: 'Малыши и Летающие звери - Добрые истории' },
    { id: 't2ycMgAW6u8', name: 'Pocoyo - Learning Through Laughter' },
];
