export const VIDEOS = [
    // Русские мультики
    { id: 'ZcZVtt-baas', name: 'Маша и Медведь - Сборник лучших серий' },
    { id: 'kFoYNforU4Y', name: 'Развивающие мультики - Большой Сборник' },
    { id: 'To5yh3rDuRs', name: 'Фиксики - Познавательные мультики' },
    { id: 'ppOWBAxT-Eg', name: 'Малышарики - Сборник весёлых серий' },
    { id: 'HIcNKigvJy0', name: 'Поезда и вагоны - Развивающие мультики' },
    { id: '1axK79unKEY', name: 'Уроки тетушки Совы - Сборник мультфильмов' },
    { id: 'OBjkNW11ujM', name: 'МилаЛуна - Мультики для детей' },
    { id: 'vrLu-gdkG6I', name: 'Синий трактор - Песенки для детей' },
    { id: 'jzZKgl_29bw', name: 'Барбоскины - Новые серии' },
    { id: 'KCJniIY2Uy4', name: 'Котики, вперед! - Все серии' },
    { id: 'NzCsLa_ec30', name: 'Грузовичок Лева - Лучшие серии' },
    { id: 't6vApLGmp6E', name: 'Смешарики Пин-код - Сборник серий' },
    { id: 'Psuuom9ZS5A', name: 'Три Кота - Сборник серий' },
    { id: 'Wec8wGSOQ6A', name: 'BabyBus - Безопасность в жизни' },
    { id: 'ur3A8uT-l3E', name: 'BabyBus - Спасатели и друзья' },
    { id: 'vMuTrVbAOcs', name: 'BabyBus - Развивающие песенки' },
    { id: 'KZSMYjmL-4g', name: 'BabyBus - Волшебные истории' },
    { id: 'q-yhcaW_ZQk', name: 'BabyBus - Песенки про машинки' },

    // Английские мультики
    { id: 'qXcMNBQnQMM', name: 'CoComelon - Kids Songs and Nursery Rhymes' },
    { id: '_pWhx7l_48g', name: 'Blippi - Educational Videos for Kids' },
    { id: 'fT-ciS7dk-U', name: 'Paw Patrol - Rescue Episodes' },
    { id: 'XqZsoesa55w', name: 'Baby Shark Dance - Animal Songs' },
    { id: '6yklSe3Ud-A', name: 'Little Baby Bum - Nursery Rhymes' },
    { id: '3FszkGtTCCw', name: 'Mother Goose Club - Nursery Rhymes' },
    { id: 'Hs0fNvQ0qaQ', name: 'Sesame Street - Elmos World' },
    { id: '-Z95SxV8PZc', name: 'ChuChu TV - Rain Rain Go Away' },
    { id: 'ttinNltX1x4', name: 'Numberblocks - Math Superpowers' },
    { id: 'ptk68qC1woI', name: 'Gracies Corner - Phonics Song' },
    { id: 'bdNbUw5FIQo', name: 'Baby Shark - Find Your Shark' },
    { id: 'RIWRqjcbJcs', name: 'Morphle - Magic Pet Adventures' },
    { id: 'XhpGp9d9jSA', name: 'Badanamu - Super Hits' },
    { id: '8deypue7SdQ', name: 'Bounce Patrol - Kids Songs' },
    { id: 'DoULakpoynA', name: 'Talking Tom - Unusual Events' },
    { id: 'eUs3h7-jKIk', name: 'Caillou - School Adventures' },
    { id: 't2ycMgAW6u8', name: 'Pocoyo - Learning Through Laughter' }
];
